# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('time', models.FloatField()),
                ('rate', models.FloatField()),
                ('type_road', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(choices=[('CHARGER', 'Charger'), ('WAREHOUSEMAN', 'Warehouseman'), ('TRANSPORTER', 'Transporter')], max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('fonction', models.CharField(choices=[('GARAGE', 'Garage'), ('RESRT AREA', 'Rest Area'), ('PAYING', 'Paying'), ('PARK', 'Park'), ('CUSTOMS', 'Customs'), ('OTHERS', 'Others')], max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(choices=[('LOADING', 'Loading'), ('UNLOADING', 'Unloading')], max_length=200)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.Position')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='arrival_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_position_set', to='position_app.Position'),
        ),
        migrations.AddField(
            model_name='link',
            name='starting_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_position_set', to='position_app.Position'),
        ),
    ]
