# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position_app', '0002_auto_20170311_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('fonction', models.CharField(choices=[('GARAGE', 'Garage'), ('RESRT AREA', 'Rest Area'), ('PAYING', 'Paying'), ('PARK', 'Park'), ('CUSTOMS', 'Customs'), ('OTHERS', 'Others')], max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.Link')),
            ],
        ),
    ]
