# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position_app', '0005_auto_20170327_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_type', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Coordonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('SEAT', 'Seat'), ('RESRT AREA', 'Rest Area'), ('PAYING', 'Paying'), ('PARK', 'Park'), ('CUSTOMS', 'Customs'), ('OTHERS', 'Others')], max_length=250)),
                ('adresse', models.TextField()),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('Postal_code', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=250)),
                ('nom', models.CharField(max_length=250)),
                ('fonction', models.CharField(max_length=250)),
                ('telefixe', models.CharField(max_length=250)),
                ('telegsm', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('coordonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.Coordonne')),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='function',
            field=models.CharField(choices=[('GARAGE', 'Garage'), ('BILLING', 'Billing'), ('DELIVERY', 'Delivery'), ('LOADING', 'Loading'), ('UNLOADING', 'Ubloading')], max_length=250),
        ),
        migrations.AddField(
            model_name='coordnum',
            name='coordonne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position_app.Coordonne'),
        ),
    ]
