# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position_app', '0006_auto_20170331_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordonne',
            old_name='Postal_code',
            new_name='postal_code',
        ),
    ]
