# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('position_app', '0007_auto_20170331_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordnum',
            name='ref',
            field=models.CharField(default=datetime.datetime(2017, 3, 31, 17, 52, 22, 236508, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
