# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOADING', 'Loading'), ('UNLOADING', 'Unloading')], max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('time_p', models.DateTimeField(editable=False)),
                ('time_r', models.DateTimeField()),
                ('state_activity', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('volume', models.FloatField()),
                ('number_zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(max_length=254)),
                ('surface_available', models.FloatField()),
                ('volume_available', models.FloatField()),
                ('weight_available', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('cell_surface', models.FloatField()),
                ('cell_volume', models.FloatField()),
                ('max_weight_cell', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('type_p', models.CharField(max_length=250)),
                ('surface_p', models.FloatField()),
                ('number_places', models.IntegerField()),
                ('available_places', models.IntegerField()),
                ('state_p', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Radius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('number_floor', models.IntegerField()),
                ('number_cell', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('state', models.BooleanField(default=False)),
                ('number_building', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number_location', models.IntegerField()),
                ('volume', models.FloatField()),
                ('total_surface', models.FloatField()),
                ('usable_surface', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Building')),
            ],
        ),
        migrations.AddField(
            model_name='support',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Zone'),
        ),
        migrations.AddField(
            model_name='radius',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Zone'),
        ),
        migrations.AddField(
            model_name='parking',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Warehouse'),
        ),
        migrations.AddField(
            model_name='celltype',
            name='radius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Radius'),
        ),
        migrations.AddField(
            model_name='cell',
            name='radius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Radius'),
        ),
        migrations.AddField(
            model_name='building',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Warehouse'),
        ),
        migrations.AddField(
            model_name='activity',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.Warehouse'),
        ),
    ]
