# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time_p',
            field=models.DateTimeField(),
        ),
    ]
