# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_auto_20170311_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='state',
            new_name='is_available',
        ),
    ]
