# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_auto_20170311_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='wh_pic',
            field=models.FileField(default=datetime.datetime(2017, 4, 7, 12, 11, 8, 786780, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
