# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_warehouse_wh_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(default=datetime.datetime(2017, 4, 7, 12, 30, 25, 200024, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
