# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_warehouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type_entrepot',
            field=models.CharField(choices=[('1', 'Entrepôt public'), ('2', 'Entrepôt privé'), ('3', 'Entrepôt ouvert'), ('4', 'Entrepôt fermés'), ('5', 'Entrepôt semi-ouverts'), ('6', 'Entrepôt A'), ('7', 'Entrepôt B'), ('8', 'Entrepôt C'), ('9', "Entrepôt d'usine"), ('10', 'Entrepôt central'), ('11', 'Entrepôt distribution'), ('12', 'Entrepôt détaillant'), ('13', 'Entrepôt particulier - Messagerie'), ('14', 'Entrepôt particulier - Frigorifique'), ('15', 'Entrepôt particulier - Pharmaceutique')], default='test', max_length=250),
            preserve_default=False,
        ),
    ]
