# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_warehouse_type_entrepot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='type_entrepot',
            new_name='warehouse_kind',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('a', 'Réception'), ('b', 'préparation de commandes'), ('c', 'stockage'), ('d', 'expédition')], max_length=250),
        ),
    ]
