# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0007_auto_20170617_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_kind',
            new_name='type_entrepot',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('LOADING', 'Loading'), ('UNLOADING', 'Unloading')], max_length=250),
        ),
    ]
