# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=250)),
                ('sub_category', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('orderer_type', models.CharField(choices=[('LOADER', 'Loader'), ('CHARTER', 'Charter')], max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='merchandise',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise_app.Orderer'),
        ),
    ]
