# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='nickname',
            field=models.CharField(default=datetime.datetime(2017, 3, 9, 14, 27, 23, 252871, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderer',
            name='orderer_type',
            field=models.CharField(choices=[('CHARTER', 'Charter'), ('LOADER', 'Loader')], max_length=250),
        ),
    ]
