# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_app', '0003_loadunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=250)),
                ('receiver_adress', models.CharField(max_length=400)),
                ('is_fragile', models.BooleanField(default=False)),
                ('loadunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise_app.LoadUnit')),
            ],
        ),
    ]
