# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_app', '0006_merchandisedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadunit',
            name='sub_category',
            field=models.CharField(default='fruiiit', max_length=400),
            preserve_default=False,
        ),
    ]
