# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_app', '0007_loadunit_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisedoc',
            name='copy_num',
            field=models.FileField(default=datetime.datetime(2017, 3, 21, 16, 38, 44, 342595, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
