# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_app', '0008_merchandisedoc_copy_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandisedoc',
            old_name='designaiton',
            new_name='designation',
        ),
    ]
