# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise_app', '0009_auto_20170328_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
